server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:~/august-test;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true
logging.level:
  org.hibernate.SQL: debug

jwt:
  secret-key: wanted-august.test_simple_project_2024_secret_key
  # 30 days
  token.expired-time-ms: 2592000000