server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/august?characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging.level:
  org.hibernate.SQL: debug

jwt:
  secret-key: wanted-august.simple_project_2024_secret_key
  # 1 day
  token.expired-time-ms: 86400000